### ISSUE TITLE
Errors getting to work on Heavy Forwarders

### ISSUE THREAD

**Issue by justinaustad1** [microsoft/AzureMonitorAddonForSplunk#45]
Hi, 

I have the add-on working properly on a test HF running on Splunk 7.0.2 and RHEL 6.9. When attempting to get this working on a production HF running Splunk 6.6.4 and RHEL 6.9 we encountered a 401 password waterfall error (see below). Then, I installed the add-on to a SH in the production environment running on Splunk 7.0.4 and RHEL 7.4 (attempting to resolve a known issue with Splunk 6.6.4 and ciphers and the Application ID and Key were not masking in this HF.) The production search head was successful, we began receiving logs, and the Application ID and Key were masked. Thinking it could be a Splunk version issue we updated the version on the production HF Splunk 6.6.4 to Splunk 7.02, but still are not receiving logs and the ID and Key did not mask. I created a new HF running Splunk 7.0.2  and RHEL 6.9, in case there was a Splunk.secrets issue causing the error, but the Application ID and Key were still not masking and no logs coming in. I received a new error on this HF. 

The 2 HF have 2 different errors: 

First installation errors:
-ERROR ExecProcessor - message from "/opt/splunk_02/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://ActivityLog_TestHF Error 401 in the password waterfall: {1}
-ERROR ExecProcessor - message from "/opt/splunk_02/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://ActivityLog_TestHF Error getting secrets from storagePasswords: {"response":{"headers":{"date":"Wed, 20 Jun 2018 15:55:14 GMT","cache-control":"private","content-type":"application/json; charset=UTF-8","x-content-type-options":"nosniff","content-length":"71","vary":"Authorization","connection":"Close","x-frame-options":"SAMEORIGIN","server":"Splunkd"},"statusCode":401},"status":401,"data":{"messages":[{"type":"WARN","text":"call not properly authenticated"}]},"error":null}
-ERROR ExecProcessor - message from "/opt/splunk_02/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://ActivityLog_TestHF Error creating storage passwords: {"response":{"headers":{"date":"Wed, 20 Jun 2018 15:55:14 GMT","cache-control":"private","content-type":"application/json; charset=UTF-8","x-content-type-options":"nosniff","content-length":"71","vary":"Authorization","connection":"Close","x-frame-options":"SAMEORIGIN","server":"Splunkd"},"statusCode":401},"status":401,"data":{"messages":[{"type":"WARN","text":"call not properly authenticated"}]},"error":null}

Second installation errors:
-ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at process._tickCallback (internal/process/next_tick.js:104:9)
-ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at _combinedTickCallback (internal/process/next_tick.js:80:11)
-ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at emitErrorNT (net.js:1277:8)

Any help on these errors would be very appreciated. 
-Thanks

**Comment by sebastus** [comment]
Start with debugging configuration, just to be absolutely sure. 6.6 was released at about the same time that the password masking logic was written, so it's less likely to me that the problem is a change in Splunk code. also, let's run through it with debug logging turned on to see what else we can learn.

**Comment by tbarners** [comment]
Were you ever able to resolve this issue?  If so, can you please let me know how? -  Thank you!

**Comment by tbarners** [comment]
> Were you ever able to resolve this issue? If so, can you please let me know how? - Thank you!

Issue was resolved.  Looks like the add on requires standard Splunk port 8089 but Heavy Forwarder was setup using a different port.

**Comment by lastaill** [comment]
We saw the same error message on our heavy forwarder around the same time we stopped receiving logs from Event Hub. Eventually we started getting logs again, without having to do anything on the Splunk or Azure side, but the errors are still coming in. We've been using the recommended ports for Event Hub (5671 and 5672), not 8089, but we've been using those same ports the whole time.

Any idea what could be going on?

`-ERROR ExecProcessor - message from "/opt/splunk_02/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://ActivityLog_TestHF Error creating storage passwords: {"response":{"headers":{"date":"Wed, 20 Jun 2018 15:55:14 GMT","cache-control":"private","content-type":"application/json; charset=UTF-8","x-content-type-options":"nosniff","content-length":"71","vary":"Authorization","connection":"Close","x-frame-options":"SAMEORIGIN","server":"Splunkd"},"statusCode":401},"status":401,"data":{"messages":[{"type":"WARN","text":"call not properly authenticated"}]},"error":null}`
